apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/dsanchor/quarkus-petclinic
  newName: image-registry.openshift-image-registry.svc.cluster.local:5000/borjareinares/quarkus-petclinic
  newTag: 43e3f6e320fc532db5e482332ab709f8fe60d2f9
